package javax.xml.stream;
public interface XMLStreamReader extends XMLStreamConstants {
    Object getProperty(String name) throws IllegalArgumentException;
    int next() throws XMLStreamException;
    void close() throws XMLStreamException;
    String getNamespaceURI(String prefix);
    boolean isStartElement();
    boolean isEndElement();
    boolean isCharacters();
    boolean isWhiteSpace();
    String getAttributeValue(String namespaceURI, String localName);
    int getAttributeCount();
    javax.xml.namespace.QName getAttributeName(int index);
    String getAttributeNamespace(int index);
    String getAttributeLocalName(int index);
    String getAttributePrefix(int index);
    String getAttributeType(int index);
    String getAttributeValue(int index);
    boolean isAttributeSpecified(int index);
    int getNamespaceCount();
    String getNamespacePrefix(int index);
    String getNamespaceURI(int index);
    javax.xml.namespace.NamespaceContext getNamespaceContext();
    int getEventType();
    String getText();
    char[] getTextCharacters();
    int getTextCharacters(int sourceStart, char[] target, int targetStart, int length) throws XMLStreamException;
    int getTextStart();
    int getTextLength();
    String getEncoding();
    boolean hasText();
    javax.xml.namespace.QName getName();
    String getLocalName();
    boolean hasName();
    String getNamespaceURI();
    String getPrefix();
    String getVersion();
    boolean isStandalone();
    boolean standaloneSet();
    String getCharacterEncodingScheme();
    String getPITarget();
    String getPIData();
    Location getLocation();
    String getElementText() throws XMLStreamException;
    int nextTag() throws XMLStreamException;
    void require(int type, String namespaceURI, String localName) throws XMLStreamException;
    boolean hasNext() throws XMLStreamException;
}